apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1  # One replica for Daniel
  selector:
    matchLabels:
      app: nginx-server
  template:
    metadata:
      labels:
        app: nginx-server
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role
                operator: In
                values:
                - server  # Specify the node role for the Nginx server
      containers:
      - name: nginx-server
        image: nginx:stable-alpine
        ports:
        - containerPort: 80
      # Add any other configuration needed for your Nginx container
