version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000" # Change the port as per your requirements  #LEFT = LOCAL HOST MACHINE'S PORT NUMBER,  RIGHT = CONTAINER'S PORT NUMBER
    volumes:
      - ./:/var/www/html
    networks:
      - laravel-network
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - "3307:3306"  # Change the host port to 3307
    environment:
      MYSQL_USERNAME: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    networks:
      - laravel-network

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
    links:
      - app
    volumes:
      - ./:/var/www/html  
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf:rw
      - ./docker/logs/nginx:/var/logs/nginx:rw
    depends_on:
      - app
      - db
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge
